name: LifestyleAPI Local
values:
  - key: baseUrl
    value: ''
  - key: userId
    value: ''
  - key: orderId
    value: ''
  - key: CustomerToken
    secret: true
  - key: AdminToken
    secret: true
  - key: jwtToken
    secret: true
